[config]
schemaVersion = "0.0.1"

[package]
namespace = "MaxWasUnavailable"
name = "LethalAchievements"
description = "A framework for creating and managing achievements in Lethal Company."
websiteUrl = "https://github.com/MaxWasUnavailable/LethalAchievements"
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"

[build]
icon = "icon_256x256.png"
readme = "../README.md"
outdir = "../dist"

[[build.copy]]
source = "../LICENSE"
target = "/"

[[build.copy]]
source = "../CHANGELOG.md"
target = "/"

[[build.copy]]
source = "../LethalAchievements/bin/Release/netstandard2.1/MaxWasUnavailable.LethalAchievements.dll"
target = "/BepInEx/plugins/LethalAchievements/"

[publish]
communities = [ "lethal-company", ]
repository = "https://thunderstore.io"
[publish.categories]
lethal-company = [ "bepinex", "mods", "libraries", "misc", "clientside" ]
